### ISSUE TITLE
多期货公司问题

### ISSUE THREAD

**Issue by yangguang760** [haoziwlh/ftdc#1]
概览了一下代码，有些疑问，请赐教。
FtdClientPool 中的pollMap以ip+port为key，以FixedChannelPool为value；则我认为，FtdClientPool 中的所有连接对brokerId及userId不敏感（FtdClientPool 中的acquire方法并未将brokerId及userId作为取连接的依据），每次发送登录，从整个pool中取一个连接，登录成功时与Spi及Session绑定。
如果上述未理解错误，则目前尚无法连接多家期货公司。
建议两种方案：
1:取消FtdClientPool的单例机制，每期货公司创建一实例。
2:在FtdClientPool获取连接的机制中加入brokerId与fixedChannelPool的对应关系。

**Comment by haoziwlh** [comment]
![image](https://user-images.githubusercontent.com/5228401/38188172-4186b07a-368d-11e8-8f49-4d316213dfdb.png)
在FtdcTraderApi接口中提供了绑定的接口 调用下就可以了

**Comment by yangguang760** [comment]
理解了，多谢！
